# Generated by Django 4.1.7 on 2023-02-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nombre', models.TextField()),
                ('tipo', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=80)),
                ('tipologia', models.CharField(max_length=80)),
                ('titular', models.CharField(max_length=80)),
                ('inversion', models.FloatField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=80)),
            ],
        ),
    ]
