# Generated by Django 4.1.7 on 2023-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.TextField(),
        ),
    ]
